config:
  start_delay: 5.0
  distance_to_ball: 0.2
  distance_to_wall: 0.2

timer:
  frequency: 10 # [Hz]

camera:
  base_position: [ 0.164, 0, 0.033 ]  # [m, m, m]
  blur_strength: 3                    # [1]
  blur_size: 5                        # [pixel]

arm:
  start_delay: 3.0
  base_position: [ 0.136, 0, 0.0463 ] # [m, m, m]
  idle_position: [ 0.4, 0.0, 0.1463 ] # [m, m, m]
  idle_pitch: 0.1                     # [rad]
  l: [ 0.0765, 0.1499, 0.15, 0.14 ]
  q_init: [ 0, 1.41, 0.1608, 0 ]
  q_min: [ -.inf, -.inf, -.inf, -.inf ]
  q_max: [ .inf, .inf, .inf, .inf ]
  w_max: [ 1, 1, 1, 1 ]

gripper:
  start_delay: 3.0
  duration: 3.0 # [s]

wheels:
  radius: 0.033         # [m]
  separation: 0.160     # [m]
  max_wheel_vel: 5.0    # [rad/s]
  max_linear_vel: 0.1   # [m/s]
  max_linear_acc: 2.5   # [m/s2]
  max_angular_vel: 0.7  # [rad/s]
  max_angular_acc: 6.0  # [rad/s2]

ball_tracker:
  radius: 0.032               # [m]
  position_stddev_time: 0.01  # [m/s]
  speed_stddev_time: 0.01     # [m/s^2]

  # Further configuration
  # in specialized configs
  
  min_radius: 5       # [pixel]
  min_area: 0.6       # [1]
  timeout: 10         # [s]

robot_tracker:
  wall_height: 0.1              # [m]
  initial_x: 0                  # [m]
  initial_y: 0                  # [m]
  initial_theta: 0              # [rad]
  drive_distance_variance: 0.1  # [m/m]
  drive_angle_variance: 0.05    # [1/m]
  measure_variance: 0.1         # [m/m]