ball_tracker:
  ball_color_min: [6,80,80]
  ball_color_min: [50,255,255]

robot_tracker:
  arena: "arena2018"
  #wall_color_min: [6,80,80]
  #wall_color_min: [50,255,255]
  #grass_color_min: [6,80,80]
  #grass_color_min: [50,255,255]