# Behavior configuration
config:
  distance_to_ball: 0.2
  distance_to_wall: 0.2
  start_delay: 5.0

# Timer configuration
timer:
  frequency: 10 # [Hz]

# Camera configuration
camera:
  # Geometry
  base_position: [ 0.164, 0, 0.033 ]  # [m, m, m]
  # Image processing
  blur_strength: 3                    # [1]
  blur_size: 5                        # [pixel]

# Arm configuration
arm:
  # Geometry
  base_position: [ 0.136, 0, 0.0463 ] # [m]
  l: [ 0.0765, 0.1499, 0.15, 0.14 ]   # [m]
  q_init: [ 0, 1.41, 0.1608, 0 ]      # [rad]
  # Limits
  q_min: [ -.inf, -.inf, -.inf, -.inf ] # [rad]
  q_max: [ .inf, .inf, .inf, .inf ]     # [rad]
  w_max: [ 1, 1, 1, 1 ]                 # [rad/s]
  # Behavior
  start_delay: 3.0                    # [s]
  idle_position: [ 0.4, 0.0, 0.1463 ] # [m]
  idle_pitch: 0.1                     # [rad]

# Gripper configuration
gripper:
  duration: 3.0 # [s]
  start_delay: 3.0

# Wheels configuration
wheels:
  # Geometry
  wheel_radius: 0.033     # [m]
  wheel_separation: 0.160 # [m]
  # Probability
  linear_stddev_linear: 0.01    # [m/m]
  angular_stddev_angular: 0.01  # [rad/rad]
  # Limits
  max_wheel_vel: 5.0    # [rad/s]
  max_linear_vel: 0.1   # [m/s]
  max_linear_acc: 2.5   # [m/s2]
  max_angular_vel: 0.7  # [rad/s]
  max_angular_acc: 6.0  # [rad/s2]

# Ball tracker configuration
ball_tracker:
  # Geometry
  ball_radius: 0.032          # [m]
  # Probability
  position_stddev_time: 0.01  # [m/s]
  speed_stddev_time: 0.01     # [m/s^2]
  # Image processing
  min_radius: 5           # [pixel]
  min_area: 0.6           # [1]
  timeout: 10             # [s]
  match_max_distance: 0.1 # [m]
  min_hue: 6              # [color]
  max_hue: 50             # [color]
  min_saturation: 80      # [color]
  max_saturation: 255     # [color]
  min_value: 110          # [color]
  max_value: 255          # [color]
  dilate_size: 5          # [pix]

# Robot tracker configuration
robot_tracker:
  # Geometry
  init_position: [ 0, 0 ]       # [m]
  init_angle: 0                 # [deg]
  arena: "arena2024"
  # Probability
  position_stddev_time: 0.01    # [m/s]
  angle_stddev_time: 0.01       # [deg/s]
  wall_angle_stddev: 0.1        # [m/m]
  wall_position_stddev: 0.1     # [m/m]
  # Image processing
  canny_threshold1: 50          # [gray]
  canny_threshold2: 200         # [gray]
  canny_aperture: 3             # [pixel]
  hough_distance_resolution: 1  # [pixel]
  hough_angle_resolution: 1     # [deg]
  hough_threshold: 150          # [gray]
  horizontal_max_angle: 10      # [deg]
  vertical_max_angle: 30        # [deg]
  match_max_a: 20               # [pixel]
  match_max_b: 10               # [deg]